theme = "plain"
icons = "awesome"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
max_width = 45
min_width = 25

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
